name: Rust Tests

on:
  push:
    branches: [ master ]
    paths: [ '**.rs', '.github/workflows/rust.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.rs', '.github/workflows/rust.yml' ]
  workflow_dispatch:
  workflow_call:
    
env:
  CARGO_TERM_COLOR: always

jobs:     
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build tests
        run: cargo build --tests
      - name: Run tests
        run: cargo test --verbose
  
  web_tests:
    name: Run web tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run Chrome tests
        run: wasm-pack test --headless --chrome
