name: Rust Tests

on:
  push:
    branches: [ master ]
    paths: [ '**.rs', './.github/workflows/rust.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.rs', './.github/workflows/rust.yml' ]
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: target
      
  unit_tests:  
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
      - name: Run tests
        run: cargo test --verbose
  
  web_tests:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run Chrome tests
        run: wasm-pack test --headless --chrome
